"use strict";
const assert = require("assert");
const fs = require("fs");
const path = require("path");

const src = fs.readFileSync(path.join(__dirname, "..", "remote-viewer.html"), "utf8");
const host = fs.readFileSync(path.join(__dirname, "..", "remote-host.html"), "utf8");
const preload = fs.readFileSync(path.join(__dirname, "..", "remote-host-preload.js"), "utf8");
const supervisor = fs.readFileSync(path.join(__dirname, "..", "services", "remote-host-supervisor.js"), "utf8");
assert.ok(src.includes("reconnectAttempt"), "viewer must track reconnect attempts");
assert.ok(src.includes("[1000, 2000, 4000, 8000, 15000]"), "viewer must use bounded reconnect backoff");
assert.ok(src.includes("signalGeneration"), "stale sockets must not schedule duplicate reconnects");
assert.ok(src.includes("authRejected"), "authentication failures must not enter an infinite reconnect loop");
assert.ok(src.includes("setTimeout(renewAdmissionAndConnect, delay)"), "viewer reconnect must mint a fresh single-use admission");
assert.ok(src.includes("remote:viewerAdmission") === false, "renderer must not select arbitrary IPC channels");
assert.ok(host.includes("_signalReconnectAttempt"), "host must track reconnect attempts");
assert.ok(host.includes("等待新登录凭证"), "host auth failure must wait for refreshed credentials");
assert.ok(host.includes("_signalReconnectTimer = setTimeout(connect, delay)"), "host reconnect must use the real signal path");
const main = fs.readFileSync(path.join(__dirname, "..", "main.js"), "utf8");
assert.ok(main.includes("_remoteHostRecoveryTimer"), "main process must supervise the hidden host independently");
assert.ok(main.includes("attemptId"), "account host state must expose a correlation id for diagnostics");
assert.ok(main.includes("RemoteHostSupervisor"), "account control socket must be owned by the main process supervisor");
assert.ok(supervisor.includes('require("ws")'), "host supervisor must use the packaged WebSocket adapter");
assert.ok(main.includes('const AccountWebSocket = require("ws")'), "production host signaling must pin the ws adapter");
assert.ok(main.includes('WebSocketImpl: AccountWebSocket'), "production must not inject Electron's mutable global WebSocket");
assert.ok(!main.includes('_remoteHostSupervisor.stop("renderer-closed")'), "media renderer loss must not unregister the control plane");
assert.ok(main.indexOf('_accountHostSupervisor().start(_remoteAcctBootstrap)') < main.indexOf('_remoteAcctWin = new BrowserWindow'),
  "host control registration must start before the media renderer");
assert.ok(main.includes('ipcMain.on("remote-host-signal-send"'), "capture renderer must use a narrow outbound signaling bridge");
assert.ok(main.includes('ipcMain.on("remote-host-ready"'), "hidden host must explicitly announce renderer readiness");
assert.ok(main.includes('_remoteAcctBootstrap'), "main must retain bootstrap until the ready handshake");
assert.ok(preload.includes('"remote-host-ready"'), "narrow preload must permit the readiness event");
assert.ok(preload.includes('"remote-host-signal-message"'), "narrow preload must permit main-owned signaling messages");
assert.ok(host.includes('ipc.send("remote-host-ready"'), "hidden host must send readiness after installing listeners");
assert.ok(host.includes('ipc.send("remote-host-signal-send"'), "account renderer must not own the authenticated socket");
assert.ok(!src.includes("openrelay.metered.ca"), "viewer must not ship third-party public TURN credentials");
assert.ok(!host.includes("openrelay.metered.ca"), "host must not ship third-party public TURN credentials");
const remoteServer = fs.readFileSync(path.join(__dirname, "..", "services", "remote-server.js"), "utf8");
assert.ok(!remoteServer.includes("openrelay.metered.ca"), "server default ICE config must not rely on a public TURN account");
console.log("remote reconnect contract: ok");
