"""V374 durable work-control protocol and side-effect boundaries."""
from __future__ import annotations

import asyncio
import json
from pathlib import Path

import pytest

pytestmark = pytest.mark.regression


def _fresh_db(tmp_db: str):
    from hashmm.api import database as db

    db.DB_PATH = Path(tmp_db)
    db._pool = None
    db.init_db()
    return db


def test_control_actions_are_capability_backed_and_revision_bound(tmp_db):
    db = _fresh_db(tmp_db)
    from hashmm.agent import work_runtime

    alice = db.create_user("control-alice", "pw12345678")
    bob = db.create_user("control-bob", "pw12345678")
    running = work_runtime.create_run(
        user_id=alice["id"], kind="loop", source_id="loop-control", status="running",
    )
    assert running["control"] == {
        "schema": "hashmm.work-control.v1",
        "expected_revision": running["revision"],
        "available_actions": ["pause", "cancel"],
        "side_effect_boundary": "checkpointed_cooperative",
    }
    chat = work_runtime.create_run(
        user_id=alice["id"], kind="chat", source_id="chat-observe", status="running",
    )
    assert chat["control"]["available_actions"] == []
    assert chat["control"]["side_effect_boundary"] == "observe_only"
    team = work_runtime.create_run(
        user_id=alice["id"], kind="team", source_id="team-stopping", status="running",
    )
    assert team["control"]["available_actions"] == ["cancel"]
    stopping = work_runtime.append_event(
        team["id"], user_id=alice["id"], event_type="stop_requested",
        status="running", snapshot_updates={"stop_requested": True},
    )
    assert stopping and stopping["control"]["available_actions"] == []

    stale = work_runtime.admit_command(
        running["id"], user_id=alice["id"], command_id="cmd-stale-0001",
        action="pause", expected_revision=running["revision"] + 1,
    )
    assert stale["state"] == "revision_conflict"
    hidden = work_runtime.admit_command(
        running["id"], user_id=bob["id"], command_id="cmd-hidden-0001",
        action="pause", expected_revision=running["revision"],
    )
    assert hidden == {"state": "not_found"}

    # Idempotency keys are scoped to an owner.  A command UUID generated by
    # another tenant must neither collide nor reveal that it already exists.
    alice_claim = work_runtime.admit_command(
        running["id"], user_id=alice["id"], command_id="cmd-shared-owner",
        action="pause", expected_revision=running["revision"],
    )
    bob_running = work_runtime.create_run(
        user_id=bob["id"], kind="loop", source_id="loop-control-bob", status="running",
    )
    bob_claim = work_runtime.admit_command(
        bob_running["id"], user_id=bob["id"], command_id="cmd-shared-owner",
        action="pause", expected_revision=bob_running["revision"],
    )
    assert alice_claim["state"] == "admitted"
    assert bob_claim["state"] == "admitted"


def test_duplicate_command_is_not_dispatched_twice(tmp_db, monkeypatch):
    db = _fresh_db(tmp_db)
    from hashmm.agent import loop_engine, work_control, work_runtime

    user = db.create_user("control-idempotent", "pw12345678")
    run = work_runtime.create_run(
        user_id=user["id"], kind="loop", source_id="loop-idempotent", status="running",
    )
    calls = {"pause": 0}

    def pause(_source: str, _owner: str) -> bool:
        calls["pause"] += 1
        return True

    monkeypatch.setattr(loop_engine, "pause_loop", pause)
    args = dict(
        run_id=run["id"], user={"uid": user["id"], "sub": "alice"},
        command_id="cmd-idempotent-0001", action="pause",
        expected_revision=run["revision"],
    )
    first = asyncio.run(work_control.execute_command(**args))
    second = asyncio.run(work_control.execute_command(**args))
    assert first["ok"] is True and first["duplicate"] is False
    assert second["ok"] is True and second["duplicate"] is True
    assert first["command"] == second["command"]
    assert calls["pause"] == 1


def test_device_cancel_only_succeeds_before_desktop_claim(tmp_db):
    db = _fresh_db(tmp_db)
    from hashmm.agent import work_control, work_runtime

    user = db.create_user("control-device", "pw12345678")
    owner = user["id"]
    db.create_file_request("device-pending", owner, "conv-device", "look up report", "desktop")
    pending = work_runtime.create_run(
        user_id=owner, kind="browser", source_id="device-pending", status="queued",
    )
    cancelled = asyncio.run(work_control.execute_command(
        pending["id"], user={"uid": owner, "sub": "device"},
        command_id="cmd-device-cancel-1", action="cancel",
        expected_revision=pending["revision"],
    ))
    assert cancelled["ok"] is True
    assert cancelled["run"]["status"] == "cancelled"
    with db._conn() as conn:
        row = conn.execute("SELECT status FROM file_requests WHERE id='device-pending'").fetchone()
    assert row["status"] == "cancelled"

    db.create_file_request("device-claimed", owner, "conv-device", "open browser", "desktop")
    assert db.update_file_request("device-claimed", owner, "processing") is True
    claimed = work_runtime.create_run(
        user_id=owner, kind="computer", source_id="device-claimed", status="queued",
    )
    rejected = asyncio.run(work_control.execute_command(
        claimed["id"], user={"uid": owner, "sub": "device"},
        command_id="cmd-device-cancel-2", action="cancel",
        expected_revision=claimed["revision"],
    ))
    assert rejected["ok"] is False
    assert rejected["error"] == "already_claimed_or_finished"
    assert rejected["run"]["status"] == "queued"


def test_team_retry_links_one_new_run_and_is_idempotent(tmp_db, monkeypatch):
    db = _fresh_db(tmp_db)
    from hashmm.agent import team, work_control, work_runtime

    user = db.create_user("control-team", "pw12345678")
    run = work_runtime.create_run(
        user_id=user["id"], kind="team", source_id="team-terminal", status="completed",
    )
    calls = {"retry": 0}

    async def retry(_user, _source):
        calls["retry"] += 1
        return {"ok": True, "team_id": "team-next", "work_run_id": "wr-next"}

    monkeypatch.setattr(team, "retry_team", retry)
    args = dict(
        run_id=run["id"], user={"uid": user["id"], "sub": "team"},
        command_id="cmd-team-retry-0001", action="retry",
        expected_revision=run["revision"],
    )
    first = asyncio.run(work_control.execute_command(**args))
    second = asyncio.run(work_control.execute_command(**args))
    assert first["ok"] is True and second["duplicate"] is True
    assert first["command"]["result"]["linked_run_id"] == "wr-next"
    assert calls["retry"] == 1


def test_command_route_validates_owner_and_returns_durable_outcome(tmp_db, monkeypatch):
    pytest.importorskip("fastapi")
    db = _fresh_db(tmp_db)
    from hashmm.agent import work_runtime
    from hashmm.api.routes import work_runtime as route

    user = db.create_user("control-route", "pw12345678")
    run = work_runtime.create_run(
        user_id=user["id"], kind="browser", source_id="route-device", status="queued",
    )
    db.create_file_request("route-device", user["id"], "conv-route", "read page", "desktop")
    monkeypatch.setattr(route, "require_auth", lambda _request: {"uid": user["id"], "sub": "route"})

    class Request:
        async def json(self):
            return {
                "command_id": "cmd-route-cancel-0001",
                "action": "cancel",
                "expected_revision": run["revision"],
            }

    response = asyncio.run(route.work_run_command(run["id"], Request()))
    body = json.loads(response.body)
    assert response.status_code == 200
    assert body["command"]["schema"] == "hashmm.work-command.v1"
    assert body["run"]["status"] == "cancelled"

    other = db.create_user("control-route-other", "pw12345678")
    monkeypatch.setattr(route, "require_auth", lambda _request: {"uid": other["id"], "sub": "other"})
    with pytest.raises(Exception) as exc:
        asyncio.run(route.work_run_command(run["id"], Request()))
    assert getattr(exc.value, "status_code", None) == 404
